[package]
name = "rustbeam"
version = "0.1.0"
authors = ["Håkon Marthinsen <hakon.marthinsen@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
num_cpus = "1.12"
png = "0.15"
sdl2 = "0.33"
